### PR TITLE
Skel

### PR DESCRIPTION
**Pull request by JGRoeder**
Index skeleton built with some sample data so people making templates have something to work from. 

Unfortunately I was also still in the process of sorting some of our build files, should have pushed these separately but I'm absent minded.

### CODE REVIEW

**Comment by bahalperin** [comment]
Looks good to me!  Nothing's sticking out that I think needs to be changed right now.  Nice job, James!

Anna, Kevin, what do you think?

**Comment by kevdonk** [comment]
I think the README.md should include a build process, as well as dependencies.
E.g.
Dependencies:
npm    (links to install instructions)
bower
gulp
grunt??
python ? (not sure, but I couldn't get the server to work on work comp)

Build Process:
bower install
npm install
gulp build                    //build site to /build
gulp connect              //start local server to display
gulp watch             // perhaps explain 
gulp clean-build    // all of these, even if you don't want to use them each time

additionally, for optimization, I think we should look into:
gulp-uglify          //min js
gulp-minify-html or gulp-htmlmin   //min html
gulp-inline-source    //inline critical css and js
gulp-webp      // convert images to webp - could lead to huge performance gains, but might be tough given that users create most of the content. should discuss

I would create this myself and push a commit, but I am afraid of doing it wrong.
I waded through the files and was able to (sort of) get the site built, but I can't get the server working and it doesn't work right for me (displays with no CSS, I think)

I might be able to figure it out when I'm at home, and can write the README, but I think we should make easy instructions so that each user doesn't have to look through config/script files to build the site

**Comment by ingikim** [comment]
I don't know why I can't access James's blog.
I've tried to access http://blog.jgroeder.com/
But I couldn't. Please send your blog posts to my email. When I can access
your blog, I will start my tasks. Sorry for late reply.

**Comment by ingikim** [comment]
If I change my network location to America with Zenmate plugin, I can
access Jame's blog. I will start my tasks.

**Pull request merged**
